### ISSUE TITLE
storyboard dim request

### ISSUE THREAD

**Issue by oofyXD** [MelonIs45/dansermenu#1]
do i have to do the storyboard dim in the json file? or on the cmd 
im just a kid but when i go to the storyboard section in the json file and put 0 in the dim (example( dim { 0 ) 
the maps wont load and im not going to put this issue in wieku's becuase he told me to "learn how to use windows" on the last issue i submitted. sorry if this is a stupid request but idk how it works

**Comment by MelonIs45** [comment]
As far as I'm aware there isn't an option specifically for storyboard dim, it's tied in with the background dim. About the maps not loading, setting the dim to 0 shouldn't break anything, from what you've sent with `(example( dim { 0 )`, the syntax wouldn't be correct; it should be like this in the file (under `Playfield.Background`):
```
"Dim": {
	"Intro": 0,
	"Normal": 0.95,
	"Breaks": 0.5
},
```
where each of the different values correspond to different parts of the run, eg: Normal would be when the map is playing, Breaks during a break etc. The value you put for them is between 0 and 1, depending on how visible you want it to be. 

Hope that helps.

**Comment by oofyXD** [comment]
thanks i figured it out
