### ISSUE TITLE
not showing beatmaps

### ISSUE THREAD

**Issue by TheExplorerForUhSomething** [MelonIs45/dansermenu#12]
when i try to select a song this happens
songs folder IS properly configured

```json
{
	"General": {
		"OsuSongsDir": "E:\\dansing\\Songs",
		"OsuSkinsDir": "E:\\dansing\\Skins",
		"DiscordPresenceOn": true,
		"UnpackOszFiles": true
	},
```

https://reinstalled-windows.shx.is/RqB8tM

https://reinstalled-windows.shx.is/SMq41Q

**Comment by MelonIs45** [comment]
the songs folder of osu! not DANSER
