### ISSUE TITLE
There is no map in the list whatsoever

### ISSUE THREAD

**Issue by BULL3TB0T** [MelonIs45/dansermenu#13]
The title says everything. Did I do something wrong? I have 5.2 version of Danser

**Comment by MelonIs45** [comment]
can you send a screenshot?

**Comment by MelonIs45** [comment]
also you probably have a 0kb danser.db file so just delete it and run the menu again, then wait for it to remake the database

**Comment by BULL3TB0T** [comment]
Nope, i have no 0kb danser.db file

https://cdn.bulletbot.cf/uploads/3dde0okt.png

**Comment by MelonIs45** [comment]
what does menu.log say?

**Comment by BULL3TB0T** [comment]
Maybe it doesn't work cuz i have 5.2 version of danser?

**Comment by BULL3TB0T** [comment]
Now i reinstalled it and still nothing

https://cdn.bulletbot.cf/uploads/t8wotz7f.png
