### ISSUE TITLE
Danser Menu Can't run even i install .net core runtime 3.1.21

### ISSUE THREAD

**Issue by minhlongdev** [MelonIs45/dansermenu#20]
it said u need to install .net core to run this app, but i alredy install
![image](https://user-images.githubusercontent.com/94881672/142964416-7edfbcad-e860-4dd9-984d-aba34098bc7c.png)
![image](https://user-images.githubusercontent.com/94881672/142964528-04319a82-d176-417d-a7ef-b8b373f0116c.png)

**Comment by MelonIs45** [comment]
that's the runtime, you need the SDK: https://dotnet.microsoft.com/download/dotnet/5.0 (top download)

try getting the 64 bit version and if that doesn't work get the x86 one aswell

**Comment by minhlongdev** [comment]
not working even i installed both
![image](https://user-images.githubusercontent.com/94881672/142998972-de8aba08-cbbb-4d53-880c-69683bc77d2d.png)

**Comment by minhlongdev** [comment]
?

**Comment by MelonIs45** [comment]
sorry but I don't really know what you can do, maybe install any dotnet version that is available xd but not sure

**Comment by MelonIs45** [comment]
closed due to inactivity, reopen if anything changes
