### ISSUE TITLE
A ton of request that can be done through multiple updates.

### ISSUE THREAD

**Issue by Kuina-chan** [MelonIs45/dansermenu#22]
1. Changing multiple setting in `default.json` without opening the file itself (discussed on Discord)
2. Adding more languages (can help with Vietnamese kekw)
3. Saving the previous session (Saving ticked boxes, map that has chosen, skins, replay path)
4. Allow danserMenu to be open without being placed in the danser folder (Add a path to danser.exe)

**Comment by MelonIs45** [comment]
Closed due to archiving
