### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Doritogon303** [MelonIs45/dansermenu#23]
**Describe the bug**
russian text in english language

**Screenshots**
![DANSER_Menu_7DFoAk6Wt0](https://user-images.githubusercontent.com/46861834/158636575-79954184-64a7-4f6c-bab1-fb93524f76b8.png)

**Logs/Files**
Please add `danser.log`, `menu.log` as well as any settings json file you are trying to use.

https://discord.is-terrible.xyz/r/danser.log
https://discord.is-terrible.xyz/r/menu.log

**System Information**
 - Danser Version: 0.6.8
 - Danser Menu Version: 4.3.0
 - Operating System: Windows 10 21h2

**Comment by MelonIs45** [comment]
Was it like this by default?

**Comment by MelonIs45** [comment]
Closed due to archiving
