### ISSUE TITLE
danser menu 3.0.1

### ISSUE THREAD

**Issue by Agus912** [MelonIs45/dansermenu#4]
how i solve this problem pls

![WhatsApp Image 2021-04-30 at 19 36 18](https://user-images.githubusercontent.com/83478973/116760499-71684680-a9eb-11eb-8b19-ba175ec06f10.jpeg)

**Comment by MelonIs45** [comment]
I don't think you have any of the danser files in the same folder, and if you do you probably haven't run danser first for it to generate the settings.json

**Comment by Agus912** [comment]
i have all of them bro


![sad](https://user-images.githubusercontent.com/83478973/116772646-ddb46b80-aa26-11eb-8a2f-b4390936b809.PNG)

**Comment by MelonIs45** [comment]
:/ what do you think the [RELEASES](https://github.com/MelonIs45/dansermenu/releases) page is for?
