### ISSUE TITLE
check boxes stay white 

### ISSUE THREAD

**Issue by Coolsuf** [MelonIs45/dansermenu#8]
the check boxes still select but there is no visual 
not selected-
![image](https://user-images.githubusercontent.com/31017611/117994934-e6eae580-b30e-11eb-9c1d-b51d1d9e5437.png)
selected- 
![image](https://user-images.githubusercontent.com/31017611/117994972-efdbb700-b30e-11eb-8f74-b4b4b7375b99.png)

**Comment by MelonIs45** [comment]
that's not to do with the app, you most likely have some specific windows animation turned off since that's the only thing that I could think of that would do something like this

**Comment by Coolsuf** [comment]
makes sense but i have no idea what setting is causing it. is there a way to use the menu without transparency? check boxes work on other apps

**Comment by MelonIs45** [comment]
that's the thing, I didn't use transparency on the buttons since the library I used doesn't support it, plus, all the other controls with transparency work so that wouldn't be the issue

**Comment by MelonIs45** [comment]
also I will prob add no transparency as an option in a later update

**Comment by MelonIs45** [comment]
Closed due to archiving
